# Imports

In [1]:
import numpy as np
import itertools
import functools
from numpy import random as random
import jax
import jax.numpy as jnp

from functools import partial
from scipy.io import loadmat

import matplotlib as mpl
from matplotlib import pyplot as plt

import pickle as pkl

from funcs import *
from models import fixed_h_MaxEnt

In [2]:
rng = random.default_rng()
key = jax.random.key(42)

In [3]:
movieBinnedSpiking = loadmat('../Data/movieBinnedSpiking.mat')

### Let's start with constant h and see what happens

In [312]:
B = 5000
N = 20
D = int(N + N*(N-1)/2)
t = 2
sigma = jax.random.choice(key,jnp.array([0,1]),(B,N),replace=True)
X = jax.random.uniform(key,D)
P_ = P_bar(sigma)
X_ = susc_bar(sigma)
obs = observables(sigma)
combs = all_combs_obs(N)

In [5]:
Maxent = fixed_h_MaxEnt()

In [6]:
movnames = movieBinnedSpiking['movnames']
ncell = movieBinnedSpiking['ncell']
nmov = movieBinnedSpiking['nmov']
nreps = movieBinnedSpiking['nreps'].flatten()
samplingFreq = movieBinnedSpiking['samplingFreq']
binned = movieBinnedSpiking['binned']

In [7]:
mov1 = binned[0:nreps[0],:,:,0]

In [8]:
mov1_2d = mov1.reshape((-1,93))
idx = rng.choice(93,20,replace=False)
mov1_sigma = mov1_2d[30:,idx]
mov1_sigma = jnp.array(mov1_sigma)

In [9]:
def fit_all_movs():
    global binned
    model = fixed_h_MaxEnt()
    for i in range(5):
        mov = binned[0:nreps[i],:,rng.choice(93,20,replace=False),i].reshape((-1,20))
        mov = mov[30:,:]
        mov = jnp.array(mov)
        Xf,ef = model.fit(mov)
        with open(f'../Data/model_params/Xf__mov{i}','wb') as f:
            pkl.dump(Xf,f)

### Dynamic h

In [ ]:
def p_h(sigma,**X):
    '''
    Input:
        - sigma: a (B,N+N*(N-1)/2) vector where the response of N neurons at time t are nonzero and nowhere, where sigma[i] corresponds to the response of the ith neuron, concatenated with the cross-correlations of each neuron at that time
        - X: a (B*N + N*(N-1)/2 , ) vector containing:
            - h: (B*N,) vector of the time-dependent field, where h[N*t + n] corresponds to the time dependent field of the nth neuron at time t
            - J: (N(N-1)/2,) vector of the fixed couplings between two neurons

    Output:
        p_h: the probability of that state at that time, given the parameters
    '''
    
    if 'X' in X.keys():
        X_ = X['X']
    else:
        X_ = jnp.concatenate((X['h'],X['J']))
    
    if 'Z' in X.keys():
        Z_ = X['Z']
    else:
        Z_ = 1

    sigma = sigma.reshape((-1,sigma.shape[-2],sigma.shape[-1]))
    M,B,D = sigma.shape
    BD = X_.shape[0]
    N = int(((BD - D) / (B-1)))
    if 't' in X.keys():
        tmask = t
    else:
        tmask = jnp.any(sigma != 0,axis = 2)

    sigmat = sigma[tmask]
    h = X_[:int(B*N)]
    J = X_[int(B*N):]
    h_m = h.reshape((B,N))
    ht = np.fromiter(map(lambda i : h_m[tmask[i]],itertools.count()),dtype = np.dtype((np.float32,N)),count=int(M))
    ht = jnp.asarray(ht)
    J = jnp.tile(J,(M,1))
    Xt = jnp.concatenate((ht,J),axis=1)

    p_h = jnp.exp(-1*(sigmat*Xt).sum(axis=1)) / Z_
    
    return jnp.squeeze(p_h)

def process_sigma(sigmat):
    '''
    Input:
        - sigmat: a (B,D) matrix of D-dimensional observables at time b
    
    Output:
        - out: a (B,B,D) matrix, where out[b=b,b=b,d] is the observable d at time b, and 0 everywhere else
    '''
    B,D = sigmat.shape
    mask = jnp.zeros((B,B,D))
    out = mask.at[jnp.arange(B),jnp.arange(B),:].set(sigmat)
    return out

def process_sigmas(big_sigma):
    '''
    Input:
        - sigma: a (M,B,D) matrix of D-dimensional observables at time b
    
    Output:
        - out: a (M*B,B,D) matrix where all sigmas have been expanded to be time_dependent
    '''
    M,B,D = big_sigma.shape
    return jnp.asarray(np.fromiter(map(process_sigma,big_sigma),dtype=np.dtype((np.float32,(B,B,D))),count=M).reshape((-1,B,D)))

def observables_h(sigma):
    '''
    Input:
        - sigma: an (M,B,N) matrix of binarized neural responses; sigmab[m,b,n] is the response of neuron n at time b, for trial m
    
    Output:
        - observables: (M,B, D = N + N*(N-1)/2) matrix of the observables
    '''
    M,B,N = sigma.shape
    corr = corrs(sigma.reshape((-1,N))).reshape((M,B,N))
    return jnp.concatenate((sigma,corr),axis=2)

def P_bar_h(sigma):
    '''
    Input:
        - sigma: an (M,B,N) matrix of binarized neural responses; sigmab[m,b,n] is the response of neuron n at time b, for trial m
    
    Output:
        - P_bar: (B*N + N*(N-1)/2) vector of the observables
    '''

    M,B,N = sigma.shape
    p_sigma = process_sigmas(observables_h(sigma))
    J = p_sigma[:,:,N:].sum(axis=0).sum(axis=0)/ (B*M)
    h = p_sigma[:,:,:N].sum(axis=0).flatten()/M
    return jnp.concatenate((h,J))

def combs_obs_h(B,N):
    '''
    Input:
        - B,N: the number of neurons, and number of time steps that neurons were recorded over
    
    Output:
        - combs_obs_h: every combination of binarized neural activity over every time step
    '''
    
    combs_obs = all_combs_obs(N)
    combs_obs_h = jnp.tile(combs_obs,(B,1,1)).swapaxes(0,1)
    return process_sigmas(combs_obs_h)

def Q_h(X,combs_obs,Z):
    tmask = jnp.tile(jnp.eye(combs_obs.shape[1]),(combs_obs.shape[0],1)).astype(bool)
    weighted_observables = combs_obs*pt(combs_obs,X=X,Z=Z).reshape(-1,1,1)
    w_o_h = weighted_observables.sum(axis=0)


In [435]:
N = 2
B = 3
c_h = combs_obs_h(B,N)
X_h =  jax.random.uniform(key,B*N + int(N*(N-1)/2))

In [440]:
c_h.shape

(12, 3, 3)

In [443]:
jnp.tile(jnp.eye(c_h.shape[1]),(c_h.shape[0],1)).astype(bool)

Array([[ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [ T

In [426]:
sig = c_h[5:7]

In [427]:
sig

Array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 1., 0.]],

       [[1., 0., 1.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)

In [431]:
p_h(sig,X=X_h)

[[False False  True]
 [ True False False]]


Array([0.5566237 , 0.56920254], dtype=float32)